database:
  image: mysql:8
  container_name: database
  environment:
    - MYSQL_ROOT_PASSWORD=pass
    - MYSQL_DATABASE=saracommerce
  volumes:
    - ~/datadir:/var/lib/mysql
  ports:
    - 3306:3306
apache:
  image: httpd:2.4
  container_name: apache
  ports:
    - 80:80
#store:
#  image: java8/store
#  container_name: store
#  links:
#    - database:mysql_host
#  ports:
#    - 8088:8088
search:
  image: es:latest
  container_name: search
  ports:
    - 9200:9200
    - 9300:9300
  volumes:
    - ~/esdata:/elasticsearch/data
jenkins:
    image: jenkins:2.46.1
    container_name: jenkins
    ports:
      - 8080:8080
      - 5000:5000
